export default {
  content: ["./index.html", "./src/**/*.{js,jsx}"],
  theme: {
    extend: {
      colors: {
        "on-secondary-container": "#006f64",
        "surface-container-low": "#eff4ff",
        "on-secondary": "#ffffff",
        "inverse-on-surface": "#eaf1ff",
        "tertiary-container": "#585be6",
        tertiary: "#3e3fcc",
        "on-secondary-fixed-variant": "#005048",
        "surface-bright": "#f8f9ff",
        "inverse-surface": "#213145",
        "surface-tint": "#0053db",
        "on-tertiary": "#ffffff",
        "on-tertiary-fixed-variant": "#2f2ebe",
        "secondary-fixed-dim": "#4fdbc8",
        "surface-variant": "#d3e4fe",
        "tertiary-fixed": "#e1e0ff",
        "on-primary-fixed-variant": "#003ea8",
        "on-secondary-fixed": "#00201c",
        error: "#ba1a1a",
        "on-primary-fixed": "#00174b",
        "tertiary-fixed-dim": "#c0c1ff",
        "on-tertiary-container": "#f1eeff",
        "surface-container-lowest": "#ffffff",
        background: "#f8f9ff",
        "on-tertiary-fixed": "#07006c",
        secondary: "#006b5f",
        "on-error-container": "#93000a",
        "primary-fixed-dim": "#b4c5ff",
        "on-primary-container": "#eeefff",
        "secondary-fixed": "#71f8e4",
        "surface-container-highest": "#d3e4fe",
        "primary-container": "#2563eb",
        "secondary-container": "#6df5e1",
        primary: "#004ac6",
        "surface-dim": "#cbdbf5",
        "on-background": "#0b1c30",
        "inverse-primary": "#b4c5ff",
        "on-primary": "#ffffff",
        "on-error": "#ffffff",
        "primary-fixed": "#dbe1ff",
        "outline-variant": "#c3c6d7",
        "error-container": "#ffdad6",
        "on-surface-variant": "#434655",
        outline: "#737686",
        "on-surface": "#0b1c30",
        "surface-container-high": "#dce9ff",
        "surface-container": "#e5eeff",
        surface: "#f8f9ff",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        md: "16px",
        "margin-mobile": "16px",
        "margin-desktop": "40px",
        gutter: "24px",
        lg: "24px",
        xs: "4px",
        sm: "8px",
        xl: "32px",
        xxl: "48px",
      },
      fontFamily: {
        "headline-lg-mobile": ["Inter"],
        "display-lg": ["Inter"],
        "body-md": ["Inter"],
        "body-sm": ["Inter"],
        "headline-md": ["Inter"],
        "label-sm": ["Inter"],
        "headline-sm": ["Inter"],
        "headline-lg": ["Inter"],
        "label-md": ["Inter"],
        "body-lg": ["Inter"],
      },
      fontSize: {
        "headline-lg-mobile": [
          "24px",
          { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "600" },
        ],
        "display-lg": [
          "48px",
          { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" },
        ],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "headline-md": [
          "24px",
          { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "600" },
        ],
        "label-sm": [
          "12px",
          { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "600" },
        ],
        "headline-sm": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "headline-lg": [
          "32px",
          { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "600" },
        ],
        "label-md": ["14px", { lineHeight: "20px", fontWeight: "500" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
      },
    },
  },
  plugins: [],
};
